### ISSUE TITLE
reddit data pydantic typing issue

### ISSUE THREAD

**Issue by WillSH97** [HumanCompatibleAI/ranking-challenge#13]
it seems that the BASIC_EXAMPLE provided and the data returned by sample_data/data_pull.py for reddit pulls is invalid according to the pydantic model defined here: https://github.com/HumanCompatibleAI/ranking-challenge/blob/main/examples/models/request.py

**Comment by raindrift** [comment]
Oh wow, how embarrassing! I need to get CI set up on this repo to prevent this kind of thing.

**Comment by raindrift** [comment]
Ok! Should be fixed by #17

**Comment by WillSH97** [comment]
great, thanks!
