### ISSUE TITLE
Can't clone this repo on Windows due to filename case collisions

### ISSUE THREAD

**Issue by aaronsnoswell** [HumanCompatibleAI/ranking-challenge#55]
Hello!

This repo currently doesn't clone properly on Windows devices because the files at `https://github.com/HumanCompatibleAI/ranking-challenge/tree/main/sample_data/facebook_data/raw/[FB|fb]_news_[posts|comments].csv` have the same names, but differ in case only.

Can one pair of these files be renamed or deleted to avoid the case collision on NFTS filesystems?

Thank you!

**Comment by raindrift** [comment]
Oh. That's no good. I thought we had fixed this, but apparently not. I'll see what I can do about it.
